- name: build solana
  become: true
  become_user: root
  shell: "git config --global --add safe.directory /mnt/{{ repo_dir }} && cd /mnt/{{ repo_dir }} && ./f"
  args:
    chdir: "/mnt/{{ repo_dir }}"
    executable: /bin/bash
